package pccth.code.review.Backend.Service;

import org.springframework.stereotype.Component;
import pccth.code.review.Backend.DTO.Response.ReportViewModel;
import pccth.code.review.Backend.DTO.Response.ReportViewModel.DebtRow;
import pccth.code.review.Backend.DTO.Response.ReportViewModel.IssueRow;
import pccth.code.review.Backend.DTO.Response.ReportViewModel.NameCount;
import pccth.code.review.Backend.DTO.Response.ReportViewModel.OwaspRow;
import pccth.code.review.Backend.DTO.Response.ReportViewModel.QualityGate;
import pccth.code.review.Backend.DTO.Response.ReportViewModel.RecRow;
import pccth.code.review.Backend.DTO.Response.ReportViewModel.ScanRow;
import pccth.code.review.Backend.DTO.Response.ReportViewModel.Security;

@Component
public class ReportMarkdownRenderer {

    public String render(ReportViewModel vm) {
        StringBuilder sb = new StringBuilder();

        sb.append("# Code Review Report\n\n");
        sb.append("**Project:** ").append(nz(vm.getProjectName())).append("\n\n");
        sb.append("- **Generated Date:** ").append(nz(vm.getGeneratedDate())).append("\n");
        sb.append("- **Generated By:** ").append(nz(vm.getGeneratedBy())).append("\n");
        sb.append("- **Date Range:** ").append(nz(vm.getDateFrom()))
                .append(" to ").append(nz(vm.getDateTo())).append("\n\n");
        sb.append("---\n\n");

        if (vm.isShowQualityGate()) {
            renderQualityGate(sb, vm.getQualityGate());
        }
        if (vm.isShowIssueBreakdown()) {
            renderIssues(sb, vm.getIssues());
        }
        if (vm.isShowSecurityAnalysis()) {
            renderSecurity(sb, vm.getSecurity());
        }
        if (vm.isShowTechnicalDebt()) {
            renderTechnicalDebt(sb, vm.getTechnicalDebt());
        }
        if (vm.isShowRecommendations()) {
            renderRecommendations(sb, vm.getRecommendations());
        }

        return sb.toString();
    }

    private void renderQualityGate(StringBuilder sb, QualityGate qg) {
        sb.append("## Quality Gate Summary\n\n");
        sb.append("- **Total Scans:** ").append(qg.getTotalScans()).append("\n");
        sb.append("- **Passed:** ").append(qg.getPassed())
                .append("  |  **Failed:** ").append(qg.getFailed()).append("\n\n");

        sb.append("### Scan History\n\n");
        appendHeader(sb, "Scan Date", "Status", "Quality Gate", "Reliability", "Security",
                "Maintainability", "Bugs", "Vulnerabilities", "Code Smells");
        if (qg.getScans().isEmpty()) {
            sb.append("\n_No scans found_\n");
        } else {
            for (ScanRow r : qg.getScans()) {
                appendRow(sb,
                        cell(r.getDate()), cell(r.getStatus()), cell(r.getQualityGate()),
                        cell(r.getReliability()), cell(r.getSecurity()), cell(r.getMaintainability()),
                        num(r.getBugs()), num(r.getVulnerabilities()), num(r.getCodeSmells()));
            }
        }
        sb.append("\n");
    }

    private void renderIssues(StringBuilder sb, java.util.List<IssueRow> issues) {
        sb.append("## Issue Breakdown\n\n");
        sb.append("_Showing open Bugs, Vulnerabilities and Security Hotspots._\n\n");
        appendHeader(sb, "Type", "Severity", "Component", "Line", "Message");
        if (issues.isEmpty()) {
            sb.append("\n_No issues found matching criteria_\n");
        } else {
            for (IssueRow r : issues) {
                appendRow(sb, cell(r.getType()), cell(r.getSeverity()), cell(r.getComponent()),
                        cell(r.getLine()), cell(r.getMessage()));
            }
        }
        sb.append("\n");
    }

    private void renderSecurity(StringBuilder sb, Security sec) {
        sb.append("## Security Analysis\n\n");
        sb.append("- **Score:** ").append(sec.getScore()).append(" / 100\n");
        sb.append("- **Risk Level:** ").append(nz(sec.getRiskLevel())).append("\n\n");

        sb.append("### Vulnerability Severity\n\n");
        appendHeader(sb, "Severity", "Count");
        if (sec.getVulnerabilities().isEmpty()) {
            sb.append("\n_No vulnerabilities_\n");
        } else {
            for (NameCount v : sec.getVulnerabilities()) {
                appendRow(sb, cell(v.getName()), num(v.getCount()));
            }
        }
        sb.append("\n");

        sb.append("### Top 5 Security Hotspots\n\n");
        appendHeader(sb, "Issue", "Count");
        if (sec.getHotIssues().isEmpty()) {
            sb.append("\n_No hotspots detected_\n");
        } else {
            for (NameCount h : sec.getHotIssues()) {
                appendRow(sb, cell(h.getName()), num(h.getCount()));
            }
        }
        sb.append("\n");

        sb.append("### OWASP Top 10 Breakdown\n\n");
        appendHeader(sb, "Category", "Issue Count", "Status");
        if (sec.getOwasp().isEmpty()) {
            sb.append("\n_No data_\n");
        } else {
            for (OwaspRow o : sec.getOwasp()) {
                appendRow(sb, cell(o.getName()), num(o.getCount()), cell(o.getStatus()));
            }
        }
        sb.append("\n");
    }

    private void renderTechnicalDebt(StringBuilder sb, java.util.List<DebtRow> debt) {
        sb.append("## Technical Debt Analysis\n\n");
        appendHeader(sb, "Scan Date", "Project", "Technical Debt", "Cost (THB)");
        if (debt.isEmpty()) {
            sb.append("\n_No scans found_\n");
        } else {
            for (DebtRow r : debt) {
                appendRow(sb, cell(r.getDate()), cell(r.getProject()), cell(r.getDebt()), cell(r.getCost()));
            }
        }
        sb.append("\n");
    }

    private void renderRecommendations(StringBuilder sb, java.util.List<RecRow> recs) {
        sb.append("## Recommendations\n\n");
        if (recs.isEmpty()) {
            sb.append("_No recommendations available_\n\n");
            return;
        }
        // Rendered as sections (not a table): the recommended-fix text comes from
        // SonarQube rule descriptions (long + HTML-laden) which would explode a table
        // and render stray <img> tags. A fenced code block keeps it complete and safe.
        int idx = 1;
        for (RecRow r : recs) {
            sb.append("### ").append(idx++).append(". [")
                    .append(inline(r.getSeverity())).append("] ")
                    .append(inline(r.getType())).append("\n\n");
            sb.append("- **Component:** ").append(inline(r.getComponent())).append("\n");
            sb.append("- **Line:** ").append(inline(r.getLine())).append("\n");
            sb.append("- **Issue:** ").append(inline(r.getMessage())).append("\n\n");
            sb.append("**Recommended Fix:**\n\n");
            appendCodeBlock(sb, r.getRecommendedFix());
            sb.append("\n");
        }
    }

    private void appendHeader(StringBuilder sb, String... headers) {
        sb.append("| ").append(String.join(" | ", headers)).append(" |\n");
        sb.append("|");
        for (int i = 0; i < headers.length; i++) {
            sb.append(" --- |");
        }
        sb.append("\n");
    }

    private void appendRow(StringBuilder sb, String... cells) {
        sb.append("| ").append(String.join(" | ", cells)).append(" |\n");
    }

    /** Escape a value for a Markdown table cell (single line, no raw HTML/pipes). */
    private String cell(String s) {
        if (s == null) {
            return "-";
        }
        String t = s.replace("|", "\\|")
                .replace("\r", " ").replace("\n", " ")
                .replace("<", "&lt;").replace(">", "&gt;")
                .trim();
        return t.isEmpty() ? "-" : t;
    }

    /** Escape a value for inline Markdown text (single line, no raw HTML). */
    private String inline(String s) {
        if (s == null) {
            return "-";
        }
        String t = s.replace("\r", " ").replace("\n", " ")
                .replace("<", "&lt;").replace(">", "&gt;")
                .trim();
        return t.isEmpty() ? "-" : t;
    }

    /**
     * Append the given content as a fenced code block. Content is emitted verbatim
     * (no HTML rendering, nothing truncated). The fence length adapts so it can never
     * be closed early by a backtick run inside the content.
     */
    private void appendCodeBlock(StringBuilder sb, String content) {
        String body = (content == null || content.isBlank())
                ? "No recommendation available" : content.strip();
        String fence = chooseFence(body);
        sb.append(fence).append("text\n");
        sb.append(body).append("\n");
        sb.append(fence).append("\n");
    }

    /** Pick a backtick fence longer than the longest backtick run inside body (min 3). */
    private String chooseFence(String body) {
        int max = 0;
        int run = 0;
        for (int i = 0; i < body.length(); i++) {
            if (body.charAt(i) == '`') {
                run++;
                if (run > max) {
                    max = run;
                }
            } else {
                run = 0;
            }
        }
        return "`".repeat(Math.max(3, max + 1));
    }

    private String num(int n) {
        return String.valueOf(n);
    }

    private String nz(String s) {
        return (s == null || s.isEmpty()) ? "-" : s;
    }
}
